language: ruby
rvm:
  - rvm 2.3.8
  - rvm 2.4.6
  - rvm 2.5.5

before_install:
  - gem update --system
  - gem install bundler

env:
  global:
    - TWILIO_ACCOUNT_SID=AC2XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    - TWILIO_AUTH_TOKEN=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    - TWILIO_NUMBER=+15551230987
