language: ruby
rvm:
  - rvm 2.2.7
  - rvm 2.3.4
  - rvm 2.4.1

env:
  global:
    - TWILIO_ACCOUNT_SID=AC2XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    - TWILIO_AUTH_TOKEN=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    - TWILIO_NUMBER=+15551230987
